/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.embarcados;

/**
 *
 * @author diogo
 */
public class JFInterface extends javax.swing.JFrame {

    Arduino arduino = new Arduino();
    /**
     * Creates new form JFInterface
     */
    public JFInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBLenOn = new javax.swing.JButton();
        jBLenOff = new javax.swing.JButton();
        jBLenClose = new javax.swing.JButton();
        jComboPort = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBLenOn.setText("Ligar");
        jBLenOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLenOnMouseClicked(evt);
            }
        });
        jBLenOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLenOnActionPerformed(evt);
            }
        });

        jBLenOff.setText("Desligar");
        jBLenOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLenOffMouseClicked(evt);
            }
        });

        jBLenClose.setText("Fechar");
        jBLenClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLenCloseMouseClicked(evt);
            }
        });
        jBLenClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLenCloseActionPerformed(evt);
            }
        });

        jComboPort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBLenOff)
                    .addComponent(jBLenClose, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBLenOn)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jComboPort, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLenOn)
                .addGap(47, 47, 47)
                .addComponent(jBLenOff)
                .addGap(44, 44, 44)
                .addComponent(jBLenClose)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLenOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLenOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLenOnActionPerformed

    private void jBLenOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLenOnMouseClicked
        arduino.comunicacaoArduino(jBLenOn);
    }//GEN-LAST:event_jBLenOnMouseClicked

    private void jBLenOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLenOffMouseClicked
        arduino.comunicacaoArduino(jBLenOff);
    }//GEN-LAST:event_jBLenOffMouseClicked

    private void jBLenCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLenCloseMouseClicked
        arduino.comunicacaoArduino(jBLenClose);
    }//GEN-LAST:event_jBLenCloseMouseClicked

    private void jBLenCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLenCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLenCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLenClose;
    private javax.swing.JButton jBLenOff;
    private javax.swing.JButton jBLenOn;
    private javax.swing.JComboBox<String> jComboPort;
    // End of variables declaration//GEN-END:variables
}
